import './globals.css'
import { Inter } from 'next/font/google'
import NextAuth, {SessionProvider} from 'next-auth/next'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel='manifest' href='maniest.json' ></link>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
